# Generated by Django 5.1.3 on 2025-02-23 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_rename_bio_userprofile_biot'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
