"""
Django settings for logs project.

Generated by 'django-admin startproject' using Django 5.1.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-qw8%v7q95(($z9fv92bhqosth$nm!2_wka^ensc$qe^-k0t7f='

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [

    
    'accounts.apps.AccountsConfig',
    'invoice.apps.InvoiceConfig',
    'django.contrib.sites',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

   
]
SITE_ID = 1  # يتطلب هذا لتحديد الموقع الافتراضي



MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'logs.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / "templates"],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'logs.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
        #'NAME': BASE_DIR / 'db.sqlite4',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

# settings.py

# إعدادات تسجيل الدخول
LOGIN_REDIRECT_URL = 'accounts:home'  # توجيه المستخدم إلى الصفحة الرئيسية بعد تسجيل الدخول
LOGOUT_REDIRECT_URL = 'accounts:home'

LOGIN_URL = 'login'  # الصفحة التي يتم توجيه المستخدم إليها إذا لم يكن مسجل الدخول

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

# ============================
# إعدادات الملفات الثابتة (Static Files)
# ============================

# الرابط الذي ستُعرض من خلاله الملفات الثابتة في الموقع
STATIC_URL = '/static/'

# المجلدات التي تحتوي على الملفات الثابتة أثناء التطوير
STATICFILES_DIRS = [
    BASE_DIR / "static",  # تأكد أن هذا المسار يشير للمجلد الصحيح
]

# مجلد لجمع الملفات الثابتة عند استخدام collectstatic
STATIC_ROOT = BASE_DIR / "staticfiles"


# إعدادات الملفات المرفوعة (Media Files)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / "media"

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# Email settings
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'  # Use your email provider's SMTP server
EMAIL_PORT = 587  # Use the appropriate port for your email provider
EMAIL_USE_TLS = True  # Enable TLS encryption
EMAIL_HOST_USER = 'berutech1@gmail.com'  # Your email address
EMAIL_HOST_PASSWORD = 'xsiw lyuk jqxw jlvh'  # Your email password
DEFAULT_FROM_EMAIL = 'berutech1@gmail.com'  # From email address

