# Generated by Django 5.1.3 on 2025-02-26 23:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='رقم الهاتف')),
                ('address', models.TextField(blank=True, null=True, verbose_name='العنوان')),
                ('shipping_company', models.CharField(blank=True, max_length=255, null=True, verbose_name='شركة الشحن')),
                ('shipping_num', models.CharField(blank=True, max_length=255, null=True, verbose_name='رقم الشحنة')),
                ('payment_method', models.CharField(blank=True, max_length=100, null=True, verbose_name='طريقة الدفع')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
                ('currency', models.CharField(blank=True, max_length=255, null=True, verbose_name='العملة')),
                ('invoice_date', models.DateField(blank=True, null=True, verbose_name='تاريخ الفاتورة')),
                ('invoice_type', models.CharField(blank=True, max_length=100, null=True, verbose_name='نوع الفاتورة')),
                ('status', models.CharField(blank=True, max_length=100, null=True, verbose_name='حالة الفاتورة')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='تاريخ الاستحقاق')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='المجموع الكلي')),
                ('uniqueId', models.CharField(blank=True, max_length=100, null=True, verbose_name='الرقم المسلسل')),
                ('slug', models.SlugField(blank=True, max_length=225, null=True, unique=True)),
                ('date_created', models.DateTimeField(blank=True, null=True)),
                ('last_updated', models.DateTimeField(blank=True, null=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='العميل')),
            ],
            options={
                'verbose_name': 'فاتورة',
                'verbose_name_plural': 'الفواتير',
            },
        ),
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='اسم المنتج')),
                ('quantity', models.PositiveIntegerField(verbose_name='الكمية')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='سعر الوحدة')),
                ('discount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='الخصم')),
                ('addition', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='الإضافة')),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='المجموع')),
                ('grand_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='المجموع الكلي')),
                ('description', models.TextField(blank=True, null=True, verbose_name='الوصف')),
                ('barcode', models.CharField(blank=True, max_length=255, null=True, verbose_name='الباركود')),
                ('image', models.ImageField(blank=True, null=True, upload_to='photo/%y/%m/%d/', verbose_name='الصورة')),
                ('tax', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='الضريبة')),
                ('slug', models.SlugField(blank=True, max_length=225, null=True, unique=True)),
                ('date_created', models.DateTimeField(blank=True, null=True)),
                ('last_updated', models.DateTimeField(blank=True, null=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='invoice.invoice', verbose_name='الفاتورة')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='invoice.product', verbose_name='المنتج')),
            ],
            options={
                'verbose_name': 'عنصر الفاتورة',
                'verbose_name_plural': 'عناصر الفواتير',
            },
        ),
    ]
