# Generated by Django 5.1.3 on 2025-04-05 20:22

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Barcode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barcode_in', models.CharField(max_length=255, unique=True, verbose_name='الباركود الداخل')),
                ('barcode_out', models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='الباركود الخارج')),
                ('suffix', models.CharField(blank=True, max_length=10, null=True, verbose_name='اللاحقة')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('uniqueId', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='الرقم المسلسل')),
                ('slug', models.SlugField(blank=True, max_length=225, null=True, unique=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
            ],
            options={
                'verbose_name': 'باركود',
                'verbose_name_plural': 'الباركودات',
            },
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency_name', models.CharField(max_length=100, verbose_name=' العملة ')),
                ('description', models.TextField(blank=True, null=True, verbose_name='البيان')),
            ],
            options={
                'verbose_name': 'العملة ',
                'verbose_name_plural': ' العملات',
            },
        ),
        migrations.CreateModel(
            name='Payment_method',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_method_name', models.CharField(blank=True, max_length=255, verbose_name=' طريقة الدفع ')),
                ('payment_method_notes', models.TextField(blank=True, verbose_name=' البيان ')),
                ('uniqueId', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='الرقم المسلسل')),
                ('slug', models.SlugField(blank=True, max_length=225, null=True, unique=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': ' طريقة الدفع',
                'verbose_name_plural': ' طرق الدفع',
            },
        ),
        migrations.CreateModel(
            name='PriceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نوع السعر')),
                ('description', models.TextField(blank=True, null=True, verbose_name='الوصف')),
            ],
            options={
                'verbose_name': 'نوع السعر',
                'verbose_name_plural': 'أنواع الأسعار',
            },
        ),
        migrations.CreateModel(
            name='Shipping_com_m',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipping_company_name', models.CharField(blank=True, max_length=255, verbose_name=' شركة الشحن ')),
                ('notes', models.TextField(blank=True, verbose_name=' العملة ')),
                ('uniqueId', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='الرقم المسلسل')),
                ('slug', models.SlugField(blank=True, max_length=225, null=True, unique=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'شركة الشحن',
                'verbose_name_plural': 'شركات الشحن',
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_types', models.CharField(max_length=255, verbose_name='حالة الفاتورة')),
                ('status_description', models.TextField(blank=True, null=True, verbose_name='الوصف')),
                ('uniqueId', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='الرقم المسلسل')),
                ('slug', models.SlugField(blank=True, max_length=225, null=True, unique=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'حالة الفاتورة',
                'verbose_name_plural': 'حالة الفوالفواتير',
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='رقم الهاتف')),
                ('address', models.TextField(blank=True, null=True, verbose_name='العنوان')),
                ('shipping_company', models.CharField(blank=True, max_length=255, null=True, verbose_name='شركة الشحن')),
                ('shipping_num', models.CharField(blank=True, max_length=255, null=True, verbose_name='رقم الشحنة')),
                ('payment_method', models.CharField(blank=True, max_length=100, null=True, verbose_name='طريقة الدفع')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
                ('invoice_date', models.DateField(blank=True, null=True, verbose_name='تاريخ الفاتورة')),
                ('invoice_type', models.CharField(blank=True, max_length=100, null=True, verbose_name='نوع الفاتورة')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='تاريخ الاستحقاق')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='المجموع الكلي')),
                ('uniqueId', models.CharField(blank=True, max_length=100, null=True, verbose_name='الرقم المسلسل')),
                ('slug', models.SlugField(blank=True, max_length=225, null=True, unique=True)),
                ('date_created', models.DateTimeField(blank=True, null=True)),
                ('last_updated', models.DateTimeField(blank=True, null=True)),
                ('currency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='invoice.currency', verbose_name='العملة')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='العميل')),
                ('status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='invoice.status', verbose_name='حالة الفاتورة')),
            ],
            options={
                'verbose_name': 'فاتورة',
                'verbose_name_plural': 'الفواتير',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255, verbose_name='اسم المادة')),
                ('purchase_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='سعر الشراء')),
                ('profit_rate', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='نسبة الربح')),
                ('tax', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='الضريبة')),
                ('barcode', models.CharField(max_length=100, unique=True, verbose_name='الباركود')),
                ('description', models.TextField(blank=True, null=True, verbose_name='الوصف')),
                ('uniqueId', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='الرقم المسلسل')),
                ('slug', models.SlugField(blank=True, max_length=225, null=True, unique=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('price_types', models.ManyToManyField(to='invoice.pricetype', verbose_name='أنواع الأسعار')),
            ],
            options={
                'verbose_name': 'مادة',
                'verbose_name_plural': 'المواد',
            },
        ),
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255, verbose_name='اسم المنتج')),
                ('quantity', models.PositiveIntegerField(verbose_name='الكمية')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='سعر الوحدة')),
                ('discount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='الخصم')),
                ('addition', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='الإضافة')),
                ('tax', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='الضريبة')),
                ('image', models.ImageField(blank=True, null=True, upload_to='invoice_items/%y/%m/%d/', verbose_name='الصورة')),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='المجموع')),
                ('slug', models.SlugField(blank=True, max_length=225, null=True, unique=True, verbose_name='الرابط الفريد')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='invoice.invoice', verbose_name='الفاتورة')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='invoice.product', verbose_name='المنتج')),
            ],
            options={
                'verbose_name': 'عنصر الفاتورة',
                'verbose_name_plural': 'عناصر الفواتير',
            },
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('supplier_phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='رقم الهاتف')),
                ('purchase_address', models.TextField(blank=True, null=True, verbose_name='العنوان')),
                ('receiving_method', models.CharField(blank=True, max_length=255, null=True, verbose_name='طريقة الاستلام')),
                ('receiving_number', models.CharField(blank=True, max_length=255, null=True, verbose_name='رقم الاستلام')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
                ('purchase_date', models.DateField(blank=True, null=True, verbose_name='تاريخ الشراء')),
                ('purchase_type', models.CharField(blank=True, max_length=100, null=True, verbose_name='نوع الشراء')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='تاريخ الاستحقاق')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='المجموع الكلي')),
                ('global_discount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('global_addition', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('global_tax', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('tax_mode', models.CharField(choices=[('per-item', 'تفصيلي (لكل عنصر)'), ('global', 'إجمالي (مرة واحدة للفاتورة)')], default='per-item', max_length=20)),
                ('uniqueId', models.CharField(blank=True, max_length=100, null=True, verbose_name='الرقم المسلسل')),
                ('slug', models.SlugField(blank=True, max_length=225, null=True, unique=True)),
                ('date_created', models.DateTimeField(blank=True, null=True)),
                ('last_updated', models.DateTimeField(blank=True, null=True)),
                ('currency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='invoice.currency', verbose_name='العملة')),
                ('payment_method', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='invoice.payment_method', verbose_name='طريقة الدفع')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='المورد')),
                ('status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='invoice.status', verbose_name='حالة الفاتورة')),
            ],
            options={
                'verbose_name': 'فاتورة شراء',
                'verbose_name_plural': 'فواتير الشراء',
            },
        ),
        migrations.CreateModel(
            name='PurchaseItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=255, verbose_name='اسم الصنف')),
                ('quantity', models.PositiveIntegerField(verbose_name='الكمية')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='سعر الوحدة')),
                ('discount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='الخصم')),
                ('addition', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='الإضافة')),
                ('tax', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='الضريبة')),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='المجموع')),
                ('purchase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='invoice.purchase', verbose_name='فاتورة الشراء')),
            ],
            options={
                'verbose_name': 'عنصر فاتورة الشراء',
                'verbose_name_plural': 'عناصر فواتير الشراء',
            },
        ),
        migrations.CreateModel(
            name='PurchaseItemBarcode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_primary', models.BooleanField(default=False, verbose_name='باركود رئيسي')),
                ('barcode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoice.barcode', verbose_name='الباركود')),
                ('purchase_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoice.purchaseitem', verbose_name='عنصر الشراء')),
            ],
            options={
                'verbose_name': 'علاقة باركود عنصر شراء',
                'verbose_name_plural': 'علاقات باركود عناصر الشراء',
                'unique_together': {('purchase_item', 'barcode')},
            },
        ),
        migrations.AddField(
            model_name='purchaseitem',
            name='barcodes',
            field=models.ManyToManyField(through='invoice.PurchaseItemBarcode', to='invoice.barcode', verbose_name='الباركودات'),
        ),
    ]
