# Generated by Django 5.1.3 on 2025-04-20 00:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='purchaseitembarcode',
            options={'verbose_name': 'الباركودات المرتبطة بعنصر الشراء', 'verbose_name_plural': 'الباركودات المرتبطة بعناصر الشراء'},
        ),
        migrations.AlterUniqueTogether(
            name='purchaseitembarcode',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='purchaseitembarcode',
            name='barcode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoice.barcode'),
        ),
        migrations.AlterField(
            model_name='purchaseitembarcode',
            name='is_primary',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='purchaseitembarcode',
            name='purchase_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoice.purchaseitem'),
        ),
    ]
