# Generated by Django 5.1.3 on 2025-04-06 01:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='tax_mode',
        ),
    ]
