# Generated by Django 5.1.3 on 2025-03-10 02:21

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment_method',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_method_name', models.CharField(blank=True, max_length=255)),
                ('payment_method_notes', models.TextField(blank=True)),
                ('uniqueId', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='الرقم المسلسل')),
                ('slug', models.SlugField(blank=True, max_length=225, null=True, unique=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': ' طريقة الدفع',
                'verbose_name_plural': ' طرق الدفع',
            },
        ),
    ]
