# Generated by Django 5.1.3 on 2025-04-01 19:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseitem',
            name='additional_barcodes',
            field=models.ManyToManyField(blank=True, related_name='additional_purchase_items', to='invoice.barcode'),
        ),
        migrations.AlterField(
            model_name='purchaseitem',
            name='barcode',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='invoice.barcode'),
        ),
    ]
