# Generated by Django 5.1.3 on 2025-03-10 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0002_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoiceitem',
            name='image',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to='invoice_items/%y/%m/%d/', verbose_name='الصورة'),
        ),
    ]
