# Generated by Django 5.1.3 on 2025-03-16 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0002_alter_purchaseitem_barcode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseitem',
            name='slug',
        ),
    ]
