# Generated by Django 5.1.3 on 2025-04-06 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0002_remove_purchase_tax_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='tax_mode',
            field=models.CharField(choices=[('per-item', 'تفصيلي (لكل عنصر)'), ('global', 'إجمالي (مرة واحدة للفاتورة)')], default='per-item', max_length=20),
        ),
    ]
