# Generated by Django 5.1.3 on 2025-04-20 00:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0002_alter_purchaseitembarcode_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='purchaseitembarcode',
            options={'verbose_name': 'علاقة باركود عنصر شراء', 'verbose_name_plural': 'علاقات باركود عناصر الشراء'},
        ),
        migrations.AlterField(
            model_name='purchaseitembarcode',
            name='barcode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoice.barcode', verbose_name='الباركود'),
        ),
        migrations.AlterField(
            model_name='purchaseitembarcode',
            name='is_primary',
            field=models.BooleanField(default=False, verbose_name='باركود رئيسي'),
        ),
        migrations.AlterField(
            model_name='purchaseitembarcode',
            name='purchase_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoice.purchaseitem', verbose_name='عنصر الشراء'),
        ),
        migrations.AlterUniqueTogether(
            name='purchaseitembarcode',
            unique_together={('purchase_item', 'barcode')},
        ),
    ]
