# Generated by Django 5.1.3 on 2025-04-23 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0003_alter_purchaseitembarcode_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseitem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='invoice_items/%y/%m/%d/', verbose_name='الصورة'),
        ),
    ]
