# Generated by Django 5.1.3 on 2025-03-22 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0003_remove_purchaseitem_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='barcode',
            old_name='barcode',
            new_name='barcode_in',
        ),
        migrations.AddField(
            model_name='barcode',
            name='barcode_out',
            field=models.CharField(default=1, max_length=255, unique=True, verbose_name='الباركود'),
            preserve_default=False,
        ),
    ]
