# Generated by Django 5.1.3 on 2025-04-02 15:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0003_alter_purchaseitem_additional_barcodes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseitem',
            name='additional_barcodes',
        ),
        migrations.RemoveField(
            model_name='purchaseitem',
            name='barcode',
        ),
        migrations.CreateModel(
            name='PurchaseItemBarcode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_primary', models.BooleanField(default=False, verbose_name='باركود رئيسي')),
                ('barcode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoice.barcode', verbose_name='الباركود')),
                ('purchase_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoice.purchaseitem', verbose_name='عنصر الشراء')),
            ],
            options={
                'verbose_name': 'علاقة باركود عنصر شراء',
                'verbose_name_plural': 'علاقات باركود عناصر الشراء',
                'unique_together': {('purchase_item', 'barcode')},
            },
        ),
        migrations.AddField(
            model_name='purchaseitem',
            name='barcodes',
            field=models.ManyToManyField(through='invoice.PurchaseItemBarcode', to='invoice.barcode', verbose_name='الباركودات'),
        ),
    ]
