# Generated by Django 5.1.3 on 2025-04-07 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0003_purchase_tax_mode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='tax_mode',
        ),
        migrations.RemoveField(
            model_name='purchaseitem',
            name='addition',
        ),
        migrations.RemoveField(
            model_name='purchaseitem',
            name='discount',
        ),
        migrations.RemoveField(
            model_name='purchaseitem',
            name='tax',
        ),
        migrations.AlterField(
            model_name='purchase',
            name='global_addition',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='الإضافة العامة'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='global_discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='الخصم العام'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='global_tax',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='الضريبة العامة (%)'),
        ),
    ]
