# Generated by Django 5.1.3 on 2025-03-02 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0003_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoiceitem',
            name='barcode',
        ),
        migrations.RemoveField(
            model_name='invoiceitem',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='invoiceitem',
            name='description',
        ),
        migrations.RemoveField(
            model_name='invoiceitem',
            name='grand_total',
        ),
        migrations.RemoveField(
            model_name='invoiceitem',
            name='last_updated',
        ),
        migrations.RemoveField(
            model_name='invoiceitem',
            name='product',
        ),
        migrations.RemoveField(
            model_name='invoiceitem',
            name='total',
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='invoice_items/%y/%m/%d/', verbose_name='الصورة'),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='product_name',
            field=models.CharField(default=1, max_length=255, verbose_name='اسم المنتج'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='slug',
            field=models.SlugField(blank=True, max_length=225, null=True, unique=True, verbose_name='الرابط الفريد'),
        ),
    ]
