# Generated by Django 5.1.3 on 2025-04-04 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0004_remove_purchaseitem_additional_barcodes_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='purchase',
            options={'verbose_name': 'فاتورة شراء', 'verbose_name_plural': 'فواتير الشراء'},
        ),
        migrations.AddField(
            model_name='purchase',
            name='global_addition',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='الإضافة العامة'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='global_discount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='الخصم العام'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='global_tax',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='الضريبة العامة (%)'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='tax_mode',
            field=models.CharField(choices=[('per-item', 'تفصيلي (لكل عنصر)'), ('global', 'إجمالي (مرة واحدة للفاتورة)')], default='per-item', max_length=20, verbose_name='طريقة حساب الضريبة'),
        ),
    ]
