# Generated by Django 5.1.3 on 2025-03-24 17:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0004_remove_barcode_purchase_remove_barcode_purchase_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='barcode',
            name='purchase',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='barcodes', to='invoice.purchase'),
        ),
        migrations.AddField(
            model_name='barcode',
            name='purchase_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='barcodes', to='invoice.purchaseitem'),
        ),
    ]
