# Generated by Django 5.1.3 on 2025-03-02 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0004_remove_invoiceitem_barcode_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='notes',
        ),
    ]
