# Generated by Django 5.1.3 on 2025-04-23 03:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0004_purchaseitem_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sale_date', models.DateField(verbose_name='تاريخ البيع')),
                ('sale_customer_phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='رقم الهاتف')),
                ('sale_address', models.TextField(blank=True, null=True, verbose_name='العنوان')),
                ('sale_receiving_method', models.CharField(blank=True, max_length=255, null=True, verbose_name='طريقة التسليم')),
                ('sale_receiving_number', models.CharField(blank=True, max_length=255, null=True, verbose_name='رقم التسليم')),
                ('sale_notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
                ('sale_invoice_date', models.DateField(blank=True, null=True, verbose_name='تاريخ الفاتورة')),
                ('sale_type', models.CharField(blank=True, max_length=100, null=True, verbose_name='نوع الفاتورة')),
                ('sale_due_date', models.DateField(blank=True, null=True, verbose_name='تاريخ الاستحقاق')),
                ('sale_total_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='المجموع الكلي')),
                ('sale_global_discount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='الخصم العام')),
                ('sale_global_addition', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='الإضافة العامة')),
                ('sale_global_tax', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='الضريبة العامة (%)')),
                ('uniqueId', models.CharField(blank=True, max_length=100, null=True, verbose_name='الرقم المسلسل')),
                ('slug', models.SlugField(blank=True, max_length=225, null=True, unique=True)),
                ('date_created', models.DateTimeField(blank=True, null=True)),
                ('last_updated', models.DateTimeField(blank=True, null=True)),
                ('sale_currency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='invoice.currency', verbose_name='العملة')),
                ('sale_customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='العميل')),
                ('sale_payment_method', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='invoice.payment_method', verbose_name='طريقة الدفع')),
                ('sale_status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='invoice.status', verbose_name='حالة الفاتورة')),
            ],
            options={
                'verbose_name': 'فاتورة بيع',
                'verbose_name_plural': 'فواتير البيع',
            },
        ),
        migrations.CreateModel(
            name='SaleItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sale_item_name', models.CharField(max_length=255, verbose_name='اسم الصنف')),
                ('sale_quantity', models.PositiveIntegerField(verbose_name='الكمية')),
                ('sale_unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='سعر الوحدة')),
                ('sale_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='المجموع')),
                ('sale_image', models.ImageField(blank=True, null=True, upload_to='invoice_items/%y/%m/%d/', verbose_name='الصورة')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='invoice.sale', verbose_name='فاتورة البيع')),
            ],
            options={
                'verbose_name': 'عنصر فاتورة البيع',
                'verbose_name_plural': 'عناصر فواتير البيع',
            },
        ),
        migrations.CreateModel(
            name='SaleItemBarcode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_primary', models.BooleanField(default=False, verbose_name='باركود رئيسي')),
                ('barcode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoice.barcode', verbose_name='الباركود')),
                ('sale_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoice.saleitem', verbose_name='عنصر البيع')),
            ],
            options={
                'verbose_name': 'علاقة باركود عنصر بيع',
                'verbose_name_plural': 'علاقات باركود عناصر البيع',
                'unique_together': {('sale_item', 'barcode')},
            },
        ),
        migrations.AddField(
            model_name='saleitem',
            name='sale_barcodes',
            field=models.ManyToManyField(through='invoice.SaleItemBarcode', to='invoice.barcode', verbose_name='الباركودات'),
        ),
    ]
