# Generated by Django 5.1.3 on 2025-04-07 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0004_remove_purchase_tax_mode_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='currency',
            options={'verbose_name': 'العملة', 'verbose_name_plural': 'العملات'},
        ),
        migrations.AlterModelOptions(
            name='payment_method',
            options={'verbose_name': 'طريقة الدفع', 'verbose_name_plural': 'طرق الدفع'},
        ),
        migrations.AlterModelOptions(
            name='status',
            options={'verbose_name': 'حالة الفاتورة', 'verbose_name_plural': 'حالات الفواتير'},
        ),
        migrations.AlterField(
            model_name='currency',
            name='currency_name',
            field=models.CharField(max_length=100, verbose_name='العملة'),
        ),
        migrations.AlterField(
            model_name='payment_method',
            name='payment_method_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='طريقة الدفع'),
        ),
        migrations.AlterField(
            model_name='payment_method',
            name='payment_method_notes',
            field=models.TextField(blank=True, verbose_name='البيان'),
        ),
    ]
