# Generated by Django 5.1.3 on 2025-03-22 02:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0004_rename_barcode_barcode_barcode_in_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='barcode',
            old_name='barcode_in',
            new_name='barcode',
        ),
        migrations.RemoveField(
            model_name='barcode',
            name='barcode_out',
        ),
    ]
