# Generated by Django 5.1.3 on 2025-04-30 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0005_sale_saleitem_saleitembarcode_saleitem_sale_barcodes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='sale_notes',
        ),
        migrations.AddField(
            model_name='sale',
            name='sale_nsote',
            field=models.TextField(blank=True, null=True, verbose_name='ملاحظات'),
        ),
        migrations.AddField(
            model_name='saleitem',
            name='sale_item_nsote',
            field=models.TextField(blank=True, null=True, verbose_name=' ملاحظات المادة '),
        ),
    ]
