# Generated by Django 5.1.3 on 2025-03-25 01:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0005_barcode_purchase_barcode_purchase_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='barcode',
            name='purchase',
        ),
        migrations.RemoveField(
            model_name='barcode',
            name='purchase_item',
        ),
    ]
