# Generated by Django 5.1.3 on 2025-04-04 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0005_alter_purchase_options_purchase_global_addition_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='global_addition',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='global_discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='global_tax',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='tax_mode',
            field=models.CharField(choices=[('per-item', 'تفصيلي (لكل عنصر)'), ('global', 'إجمالي (مرة واحدة للفاتورة)')], default='per-item', max_length=20),
        ),
    ]
