# Generated by Django 5.1.3 on 2025-04-30 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0006_remove_sale_sale_notes_sale_sale_nsote_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='saleitem',
            old_name='sale_item_nsote',
            new_name='sale_item_note',
        ),
    ]
