# Generated by Django 5.1.3 on 2025-03-25 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0006_remove_barcode_purchase_remove_barcode_purchase_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment_method',
            name='payment_method_name',
            field=models.CharField(blank=True, max_length=255, verbose_name=' طريقة الدفع '),
        ),
        migrations.AlterField(
            model_name='payment_method',
            name='payment_method_notes',
            field=models.TextField(blank=True, verbose_name=' ملاحظات طريقة الدفع '),
        ),
    ]
