# Generated by Django 5.1.3 on 2025-04-30 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0007_rename_sale_item_nsote_saleitem_sale_item_note'),
    ]

    operations = [
        migrations.RenameField(
            model_name='saleitem',
            old_name='sale_item_note',
            new_name='sale_item_notes',
        ),
    ]
