# Generated by Django 5.1.3 on 2025-03-26 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0007_alter_payment_method_payment_method_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment_method',
            name='payment_method_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='payment_method',
            name='payment_method_notes',
            field=models.TextField(blank=True),
        ),
    ]
