# Generated by Django 5.1.3 on 2025-03-06 02:42

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0008_invoiceitem_total'),
    ]

    operations = [
        migrations.CreateModel(
            name='shipping_com_m',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipping_company_name', models.CharField(blank=True, max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('uniqueId', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='الرقم المسلسل')),
                ('slug', models.SlugField(blank=True, max_length=225, null=True, unique=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'شركة الشحن',
                'verbose_name_plural': 'شركات الشحن',
            },
        ),
    ]
