# Generated by Django 5.1.3 on 2025-03-26 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0008_alter_payment_method_payment_method_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment_method',
            name='payment_method_name',
            field=models.CharField(blank=True, max_length=255, verbose_name=' طريقة الدفع '),
        ),
        migrations.AlterField(
            model_name='payment_method',
            name='payment_method_notes',
            field=models.TextField(blank=True, verbose_name=' البيان '),
        ),
        migrations.AlterField(
            model_name='shipping_com_m',
            name='notes',
            field=models.TextField(blank=True, verbose_name=' العملة '),
        ),
        migrations.AlterField(
            model_name='shipping_com_m',
            name='shipping_company_name',
            field=models.CharField(blank=True, max_length=255, verbose_name=' شركة الشحن '),
        ),
    ]
