# Generated by Django 5.1.3 on 2025-05-03 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0008_rename_sale_item_note_saleitem_sale_item_notes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sale',
            old_name='sale_nsote',
            new_name='sale_notes',
        ),
        migrations.AddField(
            model_name='sale',
            name='sale_shipping_company',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='شركة الشحن'),
        ),
    ]
