# Generated by Django 5.1.3 on 2025-05-03 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0009_rename_sale_nsote_sale_sale_notes_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sale',
            old_name='sale_notes',
            new_name='sale_nsote',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='sale_shipping_company',
        ),
    ]
