# Generated by Django 5.1.3 on 2025-03-06 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0009_shipping_com_m'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency_name', models.CharField(max_length=100, verbose_name=' العملة ')),
                ('description', models.TextField(blank=True, null=True, verbose_name='البيان')),
            ],
            options={
                'verbose_name': 'العملة ',
                'verbose_name_plural': ' العملات',
            },
        ),
    ]
