# Generated by Django 5.1.3 on 2025-05-03 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0010_rename_sale_notes_sale_sale_nsote_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sale',
            old_name='sale_nsote',
            new_name='sale_notes',
        ),
    ]
