# Generated by Django 5.1.3 on 2025-05-03 08:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0011_rename_sale_nsote_sale_sale_notes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='saleitem',
            options={},
        ),
        migrations.RemoveField(
            model_name='saleitem',
            name='sale_barcodes',
        ),
        migrations.RemoveField(
            model_name='saleitem',
            name='sale_image',
        ),
        migrations.RemoveField(
            model_name='saleitem',
            name='sale_item_name',
        ),
        migrations.RemoveField(
            model_name='saleitem',
            name='sale_item_notes',
        ),
        migrations.RemoveField(
            model_name='saleitem',
            name='sale_quantity',
        ),
        migrations.RemoveField(
            model_name='saleitem',
            name='sale_unit_price',
        ),
        migrations.AddField(
            model_name='saleitem',
            name='barcodes',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='saleitem',
            name='item_name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='saleitem',
            name='quantity',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='saleitem',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='sale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoice.sale'),
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='sale_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='الإجمالي'),
        ),
    ]
