# Generated by Django 5.1.3 on 2025-05-03 09:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0012_alter_saleitem_options_remove_saleitem_sale_barcodes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='saleitem',
            name='item_name',
        ),
        migrations.AddField(
            model_name='saleitem',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='invoice.product', verbose_name='المادة'),
            preserve_default=False,
        ),
    ]
