# Generated by Django 5.1.3 on 2025-05-03 09:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0013_remove_saleitem_item_name_saleitem_product'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='saleitembarcode',
            options={},
        ),
        migrations.AlterField(
            model_name='saleitembarcode',
            name='barcode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoice.barcode'),
        ),
        migrations.AlterField(
            model_name='saleitembarcode',
            name='sale_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoice.saleitem'),
        ),
    ]
