# Generated by Django 5.1.3 on 2025-05-03 10:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0014_alter_saleitembarcode_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='saleitem',
            name='product',
        ),
        migrations.AddField(
            model_name='saleitem',
            name='item_name',
            field=models.CharField(default=1, max_length=255, verbose_name='اسم المادة'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='barcodes',
            field=models.JSONField(blank=True, null=True, verbose_name='الباركودات'),
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='quantity',
            field=models.PositiveIntegerField(verbose_name='الكمية'),
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='sale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='invoice.sale'),
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='السعر الفردي'),
        ),
    ]
