# Generated by Django 5.1.3 on 2025-05-03 11:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0015_remove_saleitem_product_saleitem_item_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='saleitem',
            name='sale_total',
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='barcodes',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='item_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='quantity',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='sale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoice.sale'),
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
