# Generated by Django 5.1.3 on 2025-05-03 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0016_remove_saleitem_sale_total_alter_saleitem_barcodes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barcode',
            name='barcode_in',
            field=models.CharField(max_length=255, verbose_name='الباركود الداخل'),
        ),
        migrations.AlterField(
            model_name='barcode',
            name='barcode_out',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='الباركود الخارج'),
        ),
    ]
