# Generated by Django 5.1.3 on 2025-05-05 05:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0017_alter_barcode_barcode_in_alter_barcode_barcode_out'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='sale_shipping_company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='invoice.shipping_com_m', verbose_name='  شركة الشحن'),
        ),
        migrations.AddField(
            model_name='sale',
            name='shipping_num',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='رقم الشحنة'),
        ),
    ]
