# Generated by Django 5.1.3 on 2025-05-05 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0018_sale_sale_shipping_company_sale_shipping_num'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sale',
            old_name='shipping_num',
            new_name='sale_shipping_num',
        ),
    ]
