# Generated by Django 5.1.3 on 2025-05-05 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0020_alter_saleitem_options_saleitem_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleitem',
            name='sale_total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='إجمالي البند'),
        ),
    ]
