# Generated by Django 5.1.3 on 2025-05-10 14:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0021_saleitem_sale_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='sale_image',
            field=models.ImageField(blank=True, null=True, upload_to='sales/invoices/', verbose_name='صورة الفاتورة'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='sale_shipping_company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='invoice.shipping_com_m', verbose_name='شركة الشحن'),
        ),
    ]
