# Generated by Django 5.1.3 on 2025-05-10 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0022_sale_sale_image_alter_sale_sale_shipping_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleitem',
            name='sale_item_image',
            field=models.ImageField(blank=True, null=True, upload_to='sales/invoices/', verbose_name='صورة المنتج'),
        ),
    ]
