# Generated by Django 5.1.3 on 2025-05-10 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0024_remove_sale_sale_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='saleitem',
            name='sale_item_image',
        ),
    ]
