# Generated by Django 5.1.3 on 2025-05-10 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0025_remove_saleitem_sale_item_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='sale_image',
            field=models.ImageField(blank=True, null=True, upload_to='sale_image/%y/%m/%d/', verbose_name='صورة الفاتورة '),
        ),
        migrations.AddField(
            model_name='saleitem',
            name='sale_image',
            field=models.ImageField(blank=True, null=True, upload_to='sale_items_image/%y/%m/%d/', verbose_name='صورة المادة '),
        ),
    ]
