# Generated by Django 5.1.3 on 2025-05-10 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0026_sale_sale_image_saleitem_sale_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='saleitem',
            old_name='sale_image',
            new_name='sale_item_image',
        ),
    ]
