# Generated by Django 5.1.3 on 2025-05-15 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0027_rename_sale_image_saleitem_sale_item_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='سعر البيع'),
        ),
        migrations.AlterField(
            model_name='product',
            name='barcode',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='الباركود'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price_types',
            field=models.ManyToManyField(blank=True, to='invoice.pricetype', verbose_name='أنواع الأسعار'),
        ),
        migrations.AlterField(
            model_name='product',
            name='profit_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='نسبة الربح'),
        ),
        migrations.AlterField(
            model_name='product',
            name='purchase_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='سعر الشراء'),
        ),
        migrations.AlterField(
            model_name='product',
            name='tax',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='الضريبة'),
        ),
    ]
