# Generated by Django 5.1.3 on 2025-05-16 02:01

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0028_product_price_alter_product_barcode_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='saleitem',
            options={'verbose_name': 'مادة الفاتورة', 'verbose_name_plural': 'مواد الفاتورة'},
        ),
        migrations.RemoveField(
            model_name='saleitem',
            name='sale_item_image',
        ),
        migrations.AddField(
            model_name='saleitem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='sale_items/'),
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='barcodes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='item_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='quantity',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='sale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoice.sale'),
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='sale_total',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
