# Generated by Django 5.1.3 on 2025-05-16 02:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0029_alter_saleitem_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='saleitem',
            options={'verbose_name': 'بند الفاتورة', 'verbose_name_plural': 'بنود الفاتورة'},
        ),
        migrations.RemoveField(
            model_name='saleitem',
            name='image',
        ),
        migrations.AddField(
            model_name='saleitem',
            name='sale_item_image',
            field=models.ImageField(blank=True, null=True, upload_to='sale_items_image/%y/%m/%d/', verbose_name='صورة المادة '),
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='barcodes',
            field=models.JSONField(blank=True, null=True, verbose_name='الباركودات'),
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='item_name',
            field=models.CharField(max_length=255, verbose_name='اسم المادة'),
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='ملاحظات'),
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='quantity',
            field=models.PositiveIntegerField(verbose_name='الكمية'),
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='sale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='invoice.sale'),
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='sale_total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='إجمالي البند'),
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='السعر'),
        ),
    ]
