# Generated by Django 5.1.3 on 2025-05-18 18:09

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0030_alter_saleitem_options_remove_saleitem_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='sale_image',
            field=models.ImageField(blank=True, help_text='يسمح بملفات الصور فقط (jpg, jpeg, png) بحجم أقصى 2MB', max_length=150, null=True, upload_to='sale_images/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png']), django.core.validators.MaxLengthValidator(150, message='اسم الصورة يجب ألا يتجاوز 150 حرفاً')], verbose_name='صورة الفاتورة'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='sale_shipping_company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='invoice.shipping_com_m', verbose_name='شركة الشحن'),
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='sale_item_image',
            field=models.ImageField(blank=True, help_text='يسمح بملفات الصور فقط (jpg, jpeg, png) بحجم أقصى 1MB', max_length=150, null=True, upload_to='sale_items/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png']), django.core.validators.MaxLengthValidator(150, message='اسم الصورة يجب ألا يتجاوز 150 حرفاً')], verbose_name='صورة المادة'),
        ),
    ]
