# Generated by Django 5.1.3 on 2025-06-04 21:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0034_alter_sale_sale_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='sale_shipping_company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='invoice.shipping_com_m', verbose_name=' \xa0شركة الشحن'),
        ),
    ]
