# Generated by Django 5.1.3 on 2025-06-05 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0036_alter_sale_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sale',
            options={'verbose_name': 'فاتورة بيع', 'verbose_name_plural': 'فواتير البيع'},
        ),
    ]
