# Generated by Django 5.1.3 on 2025-06-05 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0039_alter_sale_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sale',
            options={'permissions': [('can_view_all_sales', 'Can view all sales records')], 'verbose_name': 'فاتورة بيع', 'verbose_name_plural': 'فواتير البيع'},
        ),
    ]
